-- MySQL Script generated by MySQL Workbench
-- Sun Aug 14 16:32:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema peluqueria_canina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema peluqueria_canina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peluqueria_canina` DEFAULT CHARACTER SET utf8mb3 ;
USE `peluqueria_canina` ;

-- -----------------------------------------------------
-- Table `peluqueria_canina`.`duenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peluqueria_canina`.`duenio` (
  `DNI` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Teléfono` INT NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `peluqueria_canina`.`perro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peluqueria_canina`.`perro` (
  `idPerro` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `DNI` INT NOT NULL,
  PRIMARY KEY (`idPerro`),
  INDEX `DNI_idx` (`DNI` ASC) INVISIBLE,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI`)
    REFERENCES `peluqueria_canina`.`duenio` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `peluqueria_canina`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peluqueria_canina`.`historial` (
  `idHistorial` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `idPerro` INT NOT NULL,
  `Descripción` VARCHAR(45) NOT NULL,
  `Monto` FLOAT NOT NULL,
  PRIMARY KEY (`idHistorial`),
  INDEX `idPerro_idx` (`idPerro` ASC) INVISIBLE,
  CONSTRAINT `idPerro`
    FOREIGN KEY (`idPerro`)
    REFERENCES `peluqueria_canina`.`perro` (`idPerro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `peluqueria_canina`.`duenio`
-- -----------------------------------------------------
START TRANSACTION;
USE `peluqueria_canina`;
INSERT INTO `peluqueria_canina`.`duenio` (`DNI`, `Nombre`, `Apellido`, `Teléfono`, `Dirección`) VALUES (21234567, 'Luisa', 'Lopez', 4473925, 'Salta 36');
INSERT INTO `peluqueria_canina`.`duenio` (`DNI`, `Nombre`, `Apellido`, `Teléfono`, `Dirección`) VALUES (34567890, 'Raul', 'Caro', 4937394, 'Maipu 651');
INSERT INTO `peluqueria_canina`.`duenio` (`DNI`, `Nombre`, `Apellido`, `Teléfono`, `Dirección`) VALUES (22345678, 'Carlos', 'Paz', 4839473, 'Grecia 1564');
INSERT INTO `peluqueria_canina`.`duenio` (`DNI`, `Nombre`, `Apellido`, `Teléfono`, `Dirección`) VALUES (28957346, 'Juan', 'Perez', 4789689, 'Belgrano 101');
INSERT INTO `peluqueria_canina`.`duenio` (`DNI`, `Nombre`, `Apellido`, `Teléfono`, `Dirección`) VALUES (23456987, 'María', 'Perez', 4652130, 'Pueyrredon 811');

COMMIT;


-- -----------------------------------------------------
-- Data for table `peluqueria_canina`.`perro`
-- -----------------------------------------------------
START TRANSACTION;
USE `peluqueria_canina`;
INSERT INTO `peluqueria_canina`.`perro` (`idPerro`, `Nombre`, `Fecha_Nacimiento`, `Sexo`, `DNI`) VALUES (01, 'Boby', '06/04/2015', 'Macho', 22345678);
INSERT INTO `peluqueria_canina`.`perro` (`idPerro`, `Nombre`, `Fecha_Nacimiento`, `Sexo`, `DNI`) VALUES (02, 'Puppy', '12/12/2012', 'Macho', 28957346);
INSERT INTO `peluqueria_canina`.`perro` (`idPerro`, `Nombre`, `Fecha_Nacimiento`, `Sexo`, `DNI`) VALUES (03, 'Manchas', '26/03/2019', 'Hembra', 21234567);
INSERT INTO `peluqueria_canina`.`perro` (`idPerro`, `Nombre`, `Fecha_Nacimiento`, `Sexo`, `DNI`) VALUES (04, 'Fido', '12/12/2021', 'Macho', 34567890);
INSERT INTO `peluqueria_canina`.`perro` (`idPerro`, `Nombre`, `Fecha_Nacimiento`, `Sexo`, `DNI`) VALUES (05, 'Blanqui', '01/05/2007', 'Hembra', 22345678);

COMMIT;


-- -----------------------------------------------------
-- Data for table `peluqueria_canina`.`historial`
-- -----------------------------------------------------
START TRANSACTION;
USE `peluqueria_canina`;
INSERT INTO `peluqueria_canina`.`historial` (`idHistorial`, `Fecha`, `idPerro`, `Descripción`, `Monto`) VALUES (01, '15/01/2021', 03, 'Corte', 2000);
INSERT INTO `peluqueria_canina`.`historial` (`idHistorial`, `Fecha`, `idPerro`, `Descripción`, `Monto`) VALUES (02, '02/02/2022', 01, 'Lavado', 1800);
INSERT INTO `peluqueria_canina`.`historial` (`idHistorial`, `Fecha`, `idPerro`, `Descripción`, `Monto`) VALUES (03, '06/06/2022', 04, 'Corte', 2500);

COMMIT;

-- Ejercicio 6
select * From historial where fecha <= 01/01/2022 and fecha >= 31/12/2022

