-- MySQL Script generated by MySQL Workbench
-- Sun Aug 14 19:08:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema beautypet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beautypet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beautypet` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `beautypet` ;

-- -----------------------------------------------------
-- Table `beautypet`.`dueño`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautypet`.`dueño` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beautypet`.`perro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautypet`.`perro` (
  `ID_Perro` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha_nac` DATE NOT NULL,
  `Sexo` CHAR(1) NOT NULL,
  `DNI_Dueño` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID_Perro`),
  INDEX `ID_Dueño_idx` (`DNI_Dueño` ASC) VISIBLE,
  CONSTRAINT `DNI_dueño`
    FOREIGN KEY (`DNI_Dueño`)
    REFERENCES `beautypet`.`dueño` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beautypet`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautypet`.`historial` (
  `ID_Historial` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Perro` INT NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `Monto` DECIMAL(45) NOT NULL,
  PRIMARY KEY (`ID_Historial`),
  INDEX `Perro_idx` (`Perro` ASC) VISIBLE,
  CONSTRAINT `Perro`
    FOREIGN KEY (`Perro`)
    REFERENCES `beautypet`.`perro` (`ID_Perro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
